apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorty-deployment
  labels:
    app: shorty
spec:
  replicas: 4
  selector:
    matchLabels:
      app: shorty
  template:
    metadata:
      labels:
        app: shorty
    spec:
      containers:
        - name: shorty
          image: pascarl/shorty:latest
          ports:
            - containerPort: 8088


---

apiVersion: v1
kind: Service
metadata:
  name: shorty-service
spec:
  type: NodePort
  selector:
    app: shorty
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30000
