name: Docker Build and Push

on:
  push:
    branches:
      - main  # Build on push to main branch
  pull_request:
    branches:
      - main  # Build on pull requests to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      API_VERSION: ${{ github.event.inputs.API_VERSION }}  # GitHub variable for
      BASE_URL: ${{ github.event.inputs.BASE_URL }}  # GitHub variable for API_KEY
      DOCKER_HUB_TOKEN: ${{ github.event.inputs.DOCKER_HUB_TOKEN }}  # GitHub variable for DATABASE_URL
      DOCKER_HUB_USERNAME: ${{ github.event.inputs.DOCKER_HUB_USERNAME }}  # GitHub variable for DATABASE_URL
      LOGGER_NAME: ${{ github.event.inputs.LOGGER_NAME }}  # GitHub variable for DATABASE_URL
      SERVER_PORT: ${{ github.event.inputs.SERVER_PORT }}  # GitHub variable for DATABASE_URL
      # Add more GitHub variables as needed for your application

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build JAR
        run: ./gradlew build -x test  # Adjust as per your build setup

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest \
            --build-arg API_KEY=${API_VERSION} \
            --build-arg DATABASE_URL=${DOCKER_HUB_TOKEN} \
            --build-arg DATABASE_URL=${DOCKER_HUB_USERNAME} \
            --build-arg DATABASE_URL=${LOGGER_NAME} \
            --build-arg DATABASE_URL=${SERVER_PORT} \
            .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.DOCKER_HUB_USERNAME }}  # GitHub variable for Docker Hub username
          password: ${{ github.event.inputs.DOCKER_HUB_TOKEN }}  # GitHub variable for Docker Hub access token

      - name: Push Docker image to Docker Hub
        run: docker push pascarl/Shorty1:latest
