name: Docker Build and Push

on:
  push:
    branches:
      - main  # Build on push to main branch
  pull_request:
    branches:
      - main  # Build on pull requests to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      API_VERSION: ${{ secrets.API_VERSION }}
      BASE_URL: ${{ secrets.BASE_URL }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      LOGGER_NAME: ${{ secrets.LOGGER_NAME }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build JAR
        run: ./gradlew build -x test  # Adjust as per your build setup

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest \
            --build-arg API_VERSION=${API_VERSION} \
            --build-arg BASE_URL=${BASE_URL} \
            --build-arg LOGGER_NAME=${LOGGER_NAME} \
            --build-arg SERVER_PORT=${SERVER_PORT} \
            .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/your-image-name:latest
